
name: Build WF

on:
  # push:
  #   branches:
  #     - main

  pull_request:
    branches:
      - main #means whenever there is PR raises from the branch which is created from main branch, trigger happens
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Maven Build
        run: mvn install

  testing:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Run tests on main branch
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle